DROP SCHEMA IF EXISTS BL_DM CASCADE;
CREATE SCHEMA IF NOT EXISTS BL_DM;

-- Create sequences
CREATE SEQUENCE BL_DM.SEQ_DIM_DATES START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_DIM_CUSTOMERS START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_DIM_VEHICLES START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_DIM_EMPLOYEES_SCD START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_DIM_LOCATIONS START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_DIM_SALES_CHANNELS START WITH 1;
CREATE SEQUENCE BL_DM.SEQ_FACT_TRANSACTIONS START WITH 1;

-- Create tables with sequences

-- DIM_DATES
CREATE TABLE IF NOT EXISTS BL_DM.DIM_DATES (
    Date_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BL_DM.SEQ_DIM_DATES'),
    Date_Full DATE NOT NULL,
    Date_Year INT NOT NULL,
    Date_Quarter INT NOT NULL,
    Date_Month INT NOT NULL,
    Date_Week INT NOT NULL,
    Date_Day INT NOT NULL,
    Date_Day_of_Week TEXT NOT NULL
);

INSERT INTO BL_DM.DIM_DATES (Date_ID, Date_Full, Date_Year, Date_Quarter, Date_Month, Date_Week, Date_Day, Date_Day_of_Week)
SELECT -1, '1900-01-01', 1900, 1, 1, 1, 1, 'n. a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_DATES WHERE Date_ID = -1);

-- DIM_CUSTOMERS
CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS (
    Customer_SURR_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BL_DM.SEQ_DIM_CUSTOMERS'),
    Customer_SRC_ID TEXT NOT NULL,
    Customer_Name TEXT NOT NULL,
    Customer_Gender TEXT,
    Customer_Age INT,
    Customer_Passport TEXT,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO BL_DM.DIM_CUSTOMERS (Customer_SURR_ID, Customer_SRC_ID, Customer_Name, Customer_Gender, Customer_Age, Customer_Passport, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n. a.', 'n. a.', 'n. a.', -1, 'n. a.', 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_CUSTOMERS WHERE Customer_SURR_ID = -1);

-- DIM_VEHICLES
CREATE TABLE IF NOT EXISTS BL_DM.DIM_VEHICLES (
    Vehicle_SURR_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BL_DM.SEQ_DIM_VEHICLES'),
    VIN_SRC_ID TEXT NOT NULL,
    Vehicle_Color TEXT,
    Vehicle_Transmission_Type TEXT,
    Vehicle_Year INT NOT NULL,
    Vehicle_Producer_ID BIGINT NOT NULL,
    Vehicle_Producer_Name TEXT NOT NULL,
    Vehicle_Model_ID BIGINT NOT NULL,
    Vehicle_Model_Name TEXT NOT NULL,
    Vehicle_Model_Electric_Type TEXT NOT NULL,
    Vehicle_Model_Electric_Range INT NOT NULL,
    Vehicle_Model_Type_CAFV TEXT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO BL_DM.DIM_VEHICLES (Vehicle_SURR_ID, VIN_SRC_ID, Vehicle_Color, Vehicle_Transmission_Type, Vehicle_Year, Vehicle_Producer_ID, Vehicle_Producer_Name, Vehicle_Model_ID, Vehicle_Model_Name, Vehicle_Model_Electric_Type, Vehicle_Model_Electric_Range, Vehicle_Model_Type_CAFV, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n. a.', 'n. a.', 'n. a.', -1, -1, 'n. a.', -1, 'n. a.', 'n. a.', -1, 'n. a.', 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_VEHICLES WHERE Vehicle_SURR_ID = -1);

-- DIM_EMPLOYEES_SCD
CREATE TABLE IF NOT EXISTS BL_DM.DIM_EMPLOYEES_SCD (
    Employee_SURR_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BL_DM.SEQ_DIM_EMPLOYEES_SCD'),
    Employee_SRC_ID TEXT NOT NULL,
    Employee_Name TEXT NOT NULL,
    Employee_Email TEXT,
    Employee_Phone TEXT,
    START_DT DATE NOT NULL,
    END_DT DATE,
    IS_ACTIVE BOOLEAN NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO BL_DM.DIM_EMPLOYEES_SCD (Employee_SURR_ID, Employee_SRC_ID, Employee_Name, Employee_Email, Employee_Phone, START_DT, END_DT, IS_ACTIVE, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n. a.', 'n. a.', 'n. a.', 'n. a.', '1900-01-01', '9999-12-31', TRUE, 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_EMPLOYEES_SCD WHERE Employee_SURR_ID = -1);

-- DIM_LOCATIONS
CREATE TABLE IF NOT EXISTS BL_DM.DIM_LOCATIONS (
    Location_SURR_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BL_DM.SEQ_DIM_LOCATIONS'),
    Location_Postal_Code_SRC_ID INT NOT NULL,
    Location_City_ID BIGINT NOT NULL,
    Location_City_Name TEXT NOT NULL,
    Location_State_ID BIGINT NOT NULL,
    Location_State_Name TEXT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO BL_DM.DIM_LOCATIONS (Location_SURR_ID, Location_Postal_Code_SRC_ID, Location_City_ID, Location_City_Name, Location_State_ID, Location_State_Name, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, -1, -1, 'n. a.', -1, 'n. a.', 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_LOCATIONS WHERE Location_SURR_ID = -1);

-- DIM_SALES_CHANNELS
CREATE TABLE IF NOT EXISTS BL_DM.DIM_SALES_CHANNELS (
    Channel_SURR_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BL_DM.SEQ_DIM_SALES_CHANNELS'),
    Channel_SRC_ID TEXT NOT NULL,
    Channel_Type TEXT NOT NULL,
    Channel_Description TEXT,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO BL_DM.DIM_SALES_CHANNELS (Channel_SURR_ID, Channel_SRC_ID, Channel_Type, Channel_Description, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n. a.', 'n. a.', 'n. a.', 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_SALES_CHANNELS WHERE Channel_SURR_ID = -1);

-- FACT_TRANSACTIONS
CREATE TABLE IF NOT EXISTS BL_DM.FACT_TRANSACTIONS (
    Transaction_SURR_ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('BL_DM.SEQ_FACT_TRANSACTIONS'),
    Transaction_SRC_ID TEXT NOT NULL,
    Event_DT_FK BIGINT NOT NULL REFERENCES BL_DM.DIM_DATES(Date_ID),
    Customer_SURR_ID_FK BIGINT NOT NULL REFERENCES BL_DM.DIM_CUSTOMERS(Customer_SURR_ID),
    Vehicle_SURR_ID_FK BIGINT NOT NULL REFERENCES BL_DM.DIM_VEHICLES(Vehicle_SURR_ID),
    Location_SURR_ID_FK BIGINT NOT NULL REFERENCES BL_DM.DIM_LOCATIONS(Location_SURR_ID),
    Employee_SURR_ID_FK BIGINT NOT NULL REFERENCES BL_DM.DIM_EMPLOYEES_SCD(Employee_SURR_ID),
    Channel_SURR_ID_FK BIGINT NOT NULL REFERENCES BL_DM.DIM_SALES_CHANNELS(Channel_SURR_ID),
    Transaction_Payment_Method_ID BIGINT DEFAULT -1,
    Transaction_Payment_Method_Name TEXT DEFAULT 'N/A',
    Transaction_Amount FLOAT NOT NULL,
    Transaction_Quantity INT DEFAULT 1,
    Transaction_Discount FLOAT DEFAULT 0,
    Transaction_Total_Amount FLOAT GENERATED ALWAYS AS ((Transaction_Amount * Transaction_Quantity) - Transaction_Discount) STORED,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Commit changes
COMMIT;