DROP TABLE IF EXISTS DIM_DATES;

CREATE TABLE IF NOT EXISTS DIM_DATES (
    DATE_ID INT PRIMARY KEY,
    DATE_FULL DATE NOT NULL,
    DATE_YEAR INT NOT NULL,
    DATE_QUARTER INT NOT NULL,
    DATE_MONTH INT NOT NULL,
    DATE_WEEK INT NOT NULL,
    DATE_DAY INT NOT NULL,
    DATE_DAY_of_WEEK TEXT NOT NULL
);

INSERT INTO DIM_DATES (DATE_ID, DATE_FULL, DATE_YEAR, DATE_QUARTER, DATE_MONTH, DATE_WEEK, DATE_DAY, DATE_DAY_of_WEEK)
SELECT 
    TO_CHAR(datum, 'YYYYMMDD')::INT AS DATE_ID,
    datum AS DATE_FULL,
    EXTRACT(YEAR FROM datum) AS DATE_YEAR,
    EXTRACT(QUARTER FROM datum) AS DATE_QUARTER,
    EXTRACT(MONTH FROM datum) AS DATE_MONTH,
    EXTRACT(ISODOW FROM datum) AS DATE_WEEK,
    EXTRACT(DAY FROM datum) AS DATE_DAY,
    TRIM(TO_CHAR(datum, 'Day')) AS DATE_DAY_of_WEEK
FROM GENERATE_SERIES('2010-01-01'::DATE, '2030-12-31'::DATE, '1 day'::INTERVAL) datum;
