-- Retrieve the top three employees who generated the most revenue in 2017
SELECT 
    s.staff_id,  -- Select the staff ID for reference
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name,  -- Concatenate first and last names of the staff
    SUM(p.amount) AS total_revenue,  -- Calculate total revenue generated by each staff member

    -- Subquery to get the last store where the staff worked based on the latest payment date
    (SELECT st.store_id  
     FROM store st
     WHERE st.store_id = s.store_id  -- Ensure the store matches the staff's current store
     ORDER BY st.store_id DESC  -- Assuming the last store is the highest ID
     LIMIT 1) AS last_store_id  
FROM payment p

-- INNER JOIN with staff to determine which staff processed the payments
INNER JOIN staff s ON p.staff_id = s.staff_id

-- Filter for payments made in the year 2017
WHERE p.payment_date >= '2017-01-01' AND p.payment_date < '2018-01-01'

-- Group by staff to aggregate revenue
GROUP BY s.staff_id, s.first_name, s.last_name 

-- Sort by total revenue in descending order to get the top three employees
ORDER BY total_revenue DESC  
LIMIT 3;  

