DROP SCHEMA IF EXISTS BL_3NF CASCADE;

CREATE SCHEMA IF NOT EXISTS BL_3NF;

CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PRODUCERS_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_MODELS_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_VEHICLES_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_STATES_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_CITIES_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_LOCATIONS_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_CUSTOMERS_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_EMPLOYEES_SCD_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_SALES_CHANNELS_SEQ START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.CE_TRANSACTIONS_SEQ START 1;


-- Create Tables
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCERS (
    Producer_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_PRODUCERS_SEQ'),
    Producer_SRC_ID TEXT NOT NULL,
    Producer_Name TEXT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_MODELS (
    Model_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_MODELS_SEQ'),
    Model_SRC_ID TEXT NOT NULL,
    Model_Name TEXT NOT NULL,
    Model_Electric_Type TEXT NOT NULL,
    Model_Electric_Range INT,
    Model_Type_CAFV TEXT,
    Producer_ID_FK BIGINT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (Producer_ID_FK) REFERENCES BL_3NF.CE_PRODUCERS(Producer_ID)
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_VEHICLES (
    Vehicle_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_VEHICLES_SEQ'),
    VIN_SRC_ID TEXT NOT NULL,
	Vehile_Color TEXT NOT NULL,
    Vehile_Transmission_Type TEXT NOT NULL,
    Vehile_Year INT NOT NULL,
	Model_ID_FK BIGINT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (Model_ID_FK) REFERENCES BL_3NF.CE_MODELS(Model_ID)
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STATES (
    State_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_STATES_SEQ'),
    State_SRC_ID TEXT NOT NULL,
    State_Name TEXT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES (
    City_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_CITIES_SEQ'),
    City_SRC_ID TEXT NOT NULL,
    City_Name TEXT NOT NULL,
    State_ID_FK BIGINT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (State_ID_FK) REFERENCES BL_3NF.CE_STATES(State_ID)
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_LOCATIONS (
    Location_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_LOCATIONS_SEQ'),
    Location_Postal_Code_SRC_ID INT NOT NULL,
    City_ID_FK BIGINT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (City_ID_FK) REFERENCES BL_3NF.CE_CITIES(City_ID)
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS (
    Customer_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_CUSTOMERS_SEQ'),
    Customer_SRC_ID INT NOT NULL,
	Customer_Passport TEXT,
    Customer_Name TEXT NOT NULL,
    Customer_Gender TEXT,
    Customer_Age INT,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS (
    Payment_Method_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_PAYMENT_METHODS_SEQ'),
    Payment_Method_SRC_ID TEXT NOT NULL,
    Payment_Method_Name TEXT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES_SCD (
    Employee_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_EMPLOYEES_SCD_SEQ'),
    Employee_SRC_ID TEXT NOT NULL,
    Employee_Name TEXT NOT NULL,
    Employee_Email TEXT,
    Employee_Phone TEXT,
    START_DT DATE NOT NULL,
    END_DT DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Unique constraint for SCD2 tracking (prevents duplicate history records)
    CONSTRAINT unique_employee_version UNIQUE (Employee_SRC_ID, START_DT, SOURCE_System)
);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES_CHANNELS (
    Sales_Channel_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_SALES_CHANNELS_SEQ'),
    Channel_SRC_ID TEXT NOT NULL,
    Channel_Type TEXT NOT NULL,
    Channel_Description TEXT,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE IF NOT EXISTS BL_3NF.CE_TRANSACTIONS (
    Transaction_ID BIGINT PRIMARY KEY DEFAULT nextval('BL_3NF.CE_TRANSACTIONS_SEQ'),
    Transaction_SRC_ID TEXT  NOT NULL,
    Transaction_DT DATE NOT NULL,
    Transaction_Price FLOAT NOT NULL,
    VIN_FK BIGINT NOT NULL,
    Customer_ID_FK BIGINT NOT NULL,
    Payment_Method_ID_FK BIGINT NOT NULL,
    Location_ID_FK BIGINT NOT NULL,
    Employee_ID_FK BIGINT NOT NULL,
    Channel_ID_FK BIGINT NOT NULL,
    SOURCE_System TEXT NOT NULL,
    SOURCE_Entity TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    TA_INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TA_UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (VIN_FK) REFERENCES BL_3NF.CE_VEHICLES(Vehicle_ID),
    FOREIGN KEY (Customer_ID_FK) REFERENCES BL_3NF.CE_CUSTOMERS(Customer_ID),
    FOREIGN KEY (Payment_Method_ID_FK) REFERENCES BL_3NF.CE_PAYMENT_METHODS(Payment_Method_ID),
    FOREIGN KEY (Location_ID_FK) REFERENCES BL_3NF.CE_LOCATIONS(Location_ID),
    FOREIGN KEY (Employee_ID_FK) REFERENCES BL_3NF.CE_EMPLOYEES_SCD(Employee_ID),
    FOREIGN KEY (Channel_ID_FK) REFERENCES BL_3NF.CE_SALES_CHANNELS(Sales_Channel_ID)
);

COMMIT;


-- Insert Default Row for CE_PRODUCERS
INSERT INTO BL_3NF.CE_PRODUCERS (Producer_ID, Producer_SRC_ID, Producer_Name, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PRODUCERS WHERE Producer_ID = -1);

-- Insert Default Row for CE_MODELS
INSERT INTO BL_3NF.CE_MODELS (Model_ID, Model_SRC_ID, Model_Name, Model_Electric_Type, Model_Electric_Range, Model_Type_CAFV, Producer_ID_FK, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', 'n.a.', -1, 'n.a.', -1, 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_MODELS WHERE Model_ID = -1);

-- Insert Default Row for CE_VEHICLES
INSERT INTO BL_3NF.CE_VEHICLES (Vehicle_ID, VIN_SRC_ID, Vehile_Color, Vehile_Transmission_Type, Vehile_Year, Model_ID_FK, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', 'n.a.', 1900, -1, 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_VEHICLES WHERE Vehicle_ID = -1);

-- Insert Default Row for CE_STATES
INSERT INTO BL_3NF.CE_STATES (State_ID, State_SRC_ID, State_Name, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STATES WHERE State_ID = -1);

-- Insert Default Row for CE_CITIES
INSERT INTO BL_3NF.CE_CITIES (City_ID, City_SRC_ID, City_Name, State_ID_FK, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', -1, 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CITIES WHERE City_ID = -1);

-- Insert Default Row for CE_LOCATIONS
INSERT INTO BL_3NF.CE_LOCATIONS (Location_ID, Location_Postal_Code_SRC_ID, City_ID_FK, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, -1, -1, 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_LOCATIONS WHERE Location_ID = -1);

-- Insert Default Row for CE_CUSTOMERS
INSERT INTO BL_3NF.CE_CUSTOMERS (Customer_ID, Customer_SRC_ID, Customer_Passport, Customer_Name, Customer_Gender, Customer_Age, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, -1, 'n.a.', 'n.a.', 'n.a.', -1, 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CUSTOMERS WHERE Customer_ID = -1);

-- Insert Default Row for CE_PAYMENT_METHODS
INSERT INTO BL_3NF.CE_PAYMENT_METHODS (Payment_Method_ID, Payment_Method_SRC_ID, Payment_Method_Name, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PAYMENT_METHODS WHERE Payment_Method_ID = -1);

-- Insert Default Row for CE_EMPLOYEES_SCD
INSERT INTO BL_3NF.CE_EMPLOYEES_SCD (Employee_ID, Employee_SRC_ID, Employee_Name, Employee_Email, Employee_Phone, START_DT, END_DT, IS_ACTIVE, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', 'n.a.', 'n.a.', '1900-01-01', '9999-12-31', TRUE, 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_EMPLOYEES_SCD WHERE Employee_ID = -1);

-- Insert Default Row for CE_SALES_CHANNELS
INSERT INTO BL_3NF.CE_SALES_CHANNELS (Sales_Channel_ID, Channel_SRC_ID, Channel_Type, Channel_Description, SOURCE_System, SOURCE_Entity, SOURCE_ID)
SELECT -1, 'n.a.', 'n.a.', 'n.a.', 'MANUAL', 'MANUAL', 'n.a.'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_SALES_CHANNELS WHERE Sales_Channel_ID = -1);

COMMIT;